services:
  mysql:
    image: mysql:8.0
    container_name: quiz-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizdb
      MYSQL_USER: quizuser
      MYSQL_PASSWORD: quizpass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u$$MYSQL_USER -p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 3s
      retries: 20
  adminer:
    image: adminer
    ports:
      - "8081:8080"
